---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  labels:
    type: cms
    author: intelliqit
spec:
  containers:
    - name: ghost
      image: ghost
      env:
        - name: NODE_ENV
          value: development
...
