---
version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    deploy:
      replicas: 3

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: intelliqit
...
